---
title: "Test_exomePeak2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##submit exomepeak2 peakcalling on server

- Test peak calling functions

```{r}
library(exomePeak2Test)

ColData_hg19 <- read.csv("~/merip_bam/coldata_hg19.csv")

parallel_peak_calling(
coldata = ColData_hg19[ColData_hg19$Perturbation == "C",],
bam_dir = "~/merip_bam",
save_dir = "~/exomepeak2_test/test_pc",
parallel_num = 9,
single_base = F
)


library(exomePeak2Test)

ColData_hg19 <- read.csv("~/merip_bam/coldata_hg19.csv")

parallel_peak_calling(
coldata = ColData_hg19[ColData_hg19$Perturbation == "C",],
bam_dir = "~/merip_bam",
save_dir = "~/exomepeak2_test/test_annot",
parallel_num = 9,
front_name = "annot_",
single_base = T
)

library(exomePeak2Test)

ColData_hg19 <- read.csv("~/merip_bam/coldata_hg19.csv")

parallel_peak_calling(
coldata = ColData_hg19[ColData_hg19$Perturbation == "C",],
bam_dir = "~/merip_bam",
save_dir = "~/exomepeak2_test/test_annot",
parallel_num = 9,
front_name = "pc_unifGC_",
single_base = F
)


library(exomePeak2Test)

ColData_hg19 <- read.csv("~/merip_bam/coldata_hg19.csv")

parallel_peak_calling(
coldata = ColData_hg19[ColData_hg19$Perturbation == "C",],
bam_dir = "~/merip_bam",
save_dir = "~/exomepeak2_test/pc_noGC",
parallel_num = 9,
front_name = "pc_noGC_",
single_base = F,
GC_correct = F
)
```

Report the peak calling results, e.x. stored summarizedExomePeaks object and analyze it in certain ways.

```{bash}
library(exomePeak2Test)

parallel_report(
pkc_dir = "~/exomepeak2_test",
pkc_prefix = "pkc_",
pkc_suffix = ".rds",
save_dir = "~/exomepeak2_GC_peaks",
parallel_num = 9,
report_function = reads_GC_plot
)
```


plot guitars

```{r}
library(exomePeak2Test)

parallel_report(
pkc_dir = "~/exomepeak2_test",
pkc_prefix = "pkc_",
pkc_suffix = ".rds",
save_dir = "~/exomepeak2_guitar_peaks",
parallel_num = 9,
front_name = "guitar_",
report_function = guitar_plot
)
```

refined

```{r}
library(exomePeak2Test)

parallel_report(
pkc_dir = "~/exomepeak2_test",
pkc_prefix = "pkc_",
pkc_suffix = ".rds",
save_dir = "~/exomepeak2_guitar_refined_peaks",
parallel_num = 9,
front_name = "guitar_",
report_function = guitar_plot_Meth
)
```

###Direct analysis with biocparallel

```{r}
library(BiocParallel)
library(exomePeak2)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(BSgenome.Hsapiens.UCSC.hg19)

file_pkc_results <- grep( ".rds", list.files("~/exomepeak2_test"), value = T )

refined_SEP_lst <- bplapply(file_pkc_results, function(x){
SEP <- readRDS(paste0("~/exomepeak2_test/",x))
SEP <- GCnormalization(SEP, Hsapiens, TxDb.Hsapiens.UCSC.hg19.knownGene)
return(glmMeth(SEP))
})
```

